
["Common configs for RedFox86's The Spice of Life 2"]
	#The sequence for the decay on the nutrition values of food. Note that each value is a flat value
	#and so they are not applied on top of each other.
	#1.0 means 100% of the nutritional value, while 0.0 means 0%.
	"Nutritional Decay" = [1.0, 1.0, 1.0, 0.75, 0.5, 0.25, 0.0]
	#The maximum food history that is stored. In other words, the mod will remember the last N foods you
	#ate, where N is the max history
	#Range: 3 ~ 100
	"Max History" = 8

